version: "3.9"

services:

  rag-api:
    build: .
    ports:
      - "8000:8000"

  rag-dashboard:
    build: .
    command: streamlit run src/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"

    depends_on:
      - rag-api